name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:
        CI: true
        DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
        GH_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
        GH_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
        GH_REDIRECT_URI: http://localhost:7890/api/v1/github/login/callback
